app:
  name: Cygnus
  host: localhost
  port: 3000
  scheme: http://

database:
  url: sqlite:///instance/database.db
  echo: false

api:
  host: localhost
  port: 8787
  debug: true
  scheme: http://

security:
  secret_key: your_secret_key_here
  jwt_secret_key: your_jwt_secret_key_here_change_in_production
  jwt_access_token_expires: 900  # 15 minutes in seconds
  jwt_refresh_token_expires: 604800  # 7 days in seconds
  jwt_algorithm: HS256
